language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - secure: Q6+be5pMqmPfqAi16t/R541rY3pFBROTXDFQVgSoNIwyRjhpiHsp8k7in/BdcCqyP0MmIx7BySAM3+Eo1UtO13xPEm9hs1o6ath4xNKj31fZ6kBVQOdRGPVARm8SBM3h+zYmrD5tOnJuElhLwKX9juXuXDWuVjTSv9UkM7Z9ZRHrr8NJTo9QkJM7D9HFjmQ/7hj7baBWzw6SO7ZOA/Ad/TL/rWj+FczyEN1CCueW4Hq9EJLJzrrWeoy2gVB0TzDZk4ePnXRu6asUOTfQHhTyJeO7hYn66xnsaeTpmbwirvhpHiCsAZrBcx6mLB6jjuq1JIadHeF/trLnlFYdFNZ6wQ4Aw9mTKhiF3YoiIzejcK29ah0AUSk2hlcpMSHPP+Zo8eX8CZjuY6Mp06Hf9l/+rlhpbNgUc/NtsqU6tJK5tBguzPDvBtrVK2AAfvdm8u+DpjyhhAiNM77Mud1+CxlyO/EU0fkcqfKcXU4C4mJGcAxZSDGXTz10ePMHgLXFvBQhIzuFrvv7Yy3DYKaTyrPSQwfQB/IdN/niO6izl81AkfDw0vySrjYkFYnqLx+VFMHO7hy5NcKBx8d7YwcbaM05tx1nakFZio04RivIXNlW9LlHukm5PRgvLDi9zR8ye67qnOFq7gkrdoUl0QhWQePO6xRblxpPjh3XRwszQzTIl10=
matrix:
  include:
    - python: '3.4'
      env:
        - TOXENV=3.4-nocov
    - python: '3.5'
      env:
        - TOXENV=3.5-nocov
    - python: '3.5'
      env:
        - TOXENV=check
    - python: '3.5'
      env:
        - TOXENV=docs
    - python: '3.5'
      env:
        - TOXENV=codacy
    - python: '3.6'
      env:
        - TOXENV=3.6-nocov
    # - python: pypy3.5-5.7.1
    #  env:
    #    - TOXENV=pypy35-nocov
install:
  - pip install tox-travis
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
