language: python

python:
  - 3.5

# branches:
#   except:
#     - gh-pages

env:
  - TOXENV=py35

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coveralls
  - python setup.py test --addopts='--cov=sokoenginepy'
  - coveralls
