language: python

# branches:
#   except:
#     - gh-pages

env:
  - TOXENV=py34
  - TOXENV=py35

install:
  - pip install coveralls

script:
  - tox

after_success:
  - python setup.py test --adopts='--cov=sokoenginepy'
  - coveralls
