language: python
sudo: false
cache: pip
os: linux
dist: trusty
env:
  global:
  - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  - SEGFAULT_SIGNALS=all
  - secure: Q6+be5pMqmPfqAi16t/R541rY3pFBROTXDFQVgSoNIwyRjhpiHsp8k7in/BdcCqyP0MmIx7BySAM3+Eo1UtO13xPEm9hs1o6ath4xNKj31fZ6kBVQOdRGPVARm8SBM3h+zYmrD5tOnJuElhLwKX9juXuXDWuVjTSv9UkM7Z9ZRHrr8NJTo9QkJM7D9HFjmQ/7hj7baBWzw6SO7ZOA/Ad/TL/rWj+FczyEN1CCueW4Hq9EJLJzrrWeoy2gVB0TzDZk4ePnXRu6asUOTfQHhTyJeO7hYn66xnsaeTpmbwirvhpHiCsAZrBcx6mLB6jjuq1JIadHeF/trLnlFYdFNZ6wQ4Aw9mTKhiF3YoiIzejcK29ah0AUSk2hlcpMSHPP+Zo8eX8CZjuY6Mp06Hf9l/+rlhpbNgUc/NtsqU6tJK5tBguzPDvBtrVK2AAfvdm8u+DpjyhhAiNM77Mud1+CxlyO/EU0fkcqfKcXU4C4mJGcAxZSDGXTz10ePMHgLXFvBQhIzuFrvv7Yy3DYKaTyrPSQwfQB/IdN/niO6izl81AkfDw0vySrjYkFYnqLx+VFMHO7hy5NcKBx8d7YwcbaM05tx1nakFZio04RivIXNlW9LlHukm5PRgvLDi9zR8ye67qnOFq7gkrdoUl0QhWQePO6xRblxpPjh3XRwszQzTIl10=
  - secure: jHMTDJ6nlU+l92ttXMZ3DxvsvUvVFv3hoFCBn1qxDFSW+Be78eruDt/AYeKqU3IRGrtf24N6eewJmR7GWrMN8kmtUCiHlLkkHnwq9mb89rvpAxGJp816/Gf1/n4CTWM2DTUYIzksg9xuAw1+njVIzFqJoPzbhD0HUojroEqzX2G1iwANI1CQe6KREFA3ZGqXj1FGBGUnWxmkXXsIa7C0pJ+m/Ed8qXZd3lqmrKxegmRwnhUpWwpRPcogAvv66/Z+wcqYT4S6D928GhfFBG2lJ7vHYU9mhN3/dAqSDj7/quYfZIrBY7E6O014Rqwa1UAtJ1npWrnuevr3TG2lC9yjPC3dLSX4XQoMtr6j5+LvAJzlroK6E38imsKNMQwd/DsJNae24dL8dqOPATNT7flx0Yrq9tY0O1XohvD/tWgiYsWNtw8o4996cDzqlgQjclcXKpiTOkLjgqW7VipentdjhJu2GDIDM+nAOqbtphfU7ChLKPtDO579udmDN/M7QSevi3y5pmj40M+I9M7RVenO4MAbu2JYfADrRmAnfJCRZnb2txIbUYo4E07HSGgD+iIeMbA6ebAWNF+JrDdh3Bhf93ibVmyV+kw1AI9YljRvh8so+anNpq/iIEN7f46n5ZU+tfb7clPWgcMx1oRCzm0RQlHMkeIluYBRUjBQSlg/nSE=
matrix:
  include:
  - python: '3.5'
    env:
    - TOXENV=3.5
  - python: '3.5'
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntu-toolchain-r/test
        packages:
        - g++-6
        - libboost-graph-dev
    env:
    - TOXENV=3.5_native_extension
    - CC=gcc-6
    - CXX=g++-6
  - python: '3.6'
    env:
    - TOXENV=3.6
  - python: '3.6'
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntu-toolchain-r/test
        packages:
        - g++-6
        - libboost-graph-dev
    env:
    - TOXENV=3.6_native_extension
    - CC=gcc-6
    - CXX=g++-6
  - python: pypy3.5
    env:
    - TOXENV=pypy3
  - python: '3.6'
    env:
    - TOXENV=check
  - python: '3.6'
    env:
    - TOXENV=docs
  - python: '3.6'
    env:
    - TOXENV=codacy
install:
- pip install tox==2.7.0
script:
- tox
