var namespacesokoengine =
[
    [ "AtomicMove", "classsokoengine_1_1AtomicMove.html", "classsokoengine_1_1AtomicMove" ],
    [ "BoardCell", "classsokoengine_1_1BoardCell.html", "classsokoengine_1_1BoardCell" ],
    [ "BoardConversionError", "classsokoengine_1_1BoardConversionError.html", "classsokoengine_1_1BoardConversionError" ],
    [ "BoardGraph", "classsokoengine_1_1BoardGraph.html", "classsokoengine_1_1BoardGraph" ],
    [ "BoardState", "classsokoengine_1_1BoardState.html", "classsokoengine_1_1BoardState" ],
    [ "BoxGoalSwitchError", "classsokoengine_1_1BoxGoalSwitchError.html", "classsokoengine_1_1BoxGoalSwitchError" ],
    [ "CellAlreadyOccupiedError", "classsokoengine_1_1CellAlreadyOccupiedError.html", "classsokoengine_1_1CellAlreadyOccupiedError" ],
    [ "Direction", "classsokoengine_1_1Direction.html", "classsokoengine_1_1Direction" ],
    [ "HashedBoardState", "classsokoengine_1_1HashedBoardState.html", "classsokoengine_1_1HashedBoardState" ],
    [ "HexobanBoard", "classsokoengine_1_1HexobanBoard.html", "classsokoengine_1_1HexobanBoard" ],
    [ "HexobanTessellation", "classsokoengine_1_1HexobanTessellation.html", "classsokoengine_1_1HexobanTessellation" ],
    [ "IllegalBoardCharacterError", "classsokoengine_1_1IllegalBoardCharacterError.html", "classsokoengine_1_1IllegalBoardCharacterError" ],
    [ "IllegalMoveError", "classsokoengine_1_1IllegalMoveError.html", "classsokoengine_1_1IllegalMoveError" ],
    [ "InvalidAtomicMoveError", "classsokoengine_1_1InvalidAtomicMoveError.html", "classsokoengine_1_1InvalidAtomicMoveError" ],
    [ "KeyError", "classsokoengine_1_1KeyError.html", "classsokoengine_1_1KeyError" ],
    [ "Mover", "classsokoengine_1_1Mover.html", "classsokoengine_1_1Mover" ],
    [ "NonPlayableBoardError", "classsokoengine_1_1NonPlayableBoardError.html", "classsokoengine_1_1NonPlayableBoardError" ],
    [ "OctobanBoard", "classsokoengine_1_1OctobanBoard.html", "classsokoengine_1_1OctobanBoard" ],
    [ "OctobanTessellation", "classsokoengine_1_1OctobanTessellation.html", "classsokoengine_1_1OctobanTessellation" ],
    [ "SokobanBoard", "classsokoengine_1_1SokobanBoard.html", "classsokoengine_1_1SokobanBoard" ],
    [ "SokobanPlus", "classsokoengine_1_1SokobanPlus.html", "classsokoengine_1_1SokobanPlus" ],
    [ "SokobanPlusDataError", "classsokoengine_1_1SokobanPlusDataError.html", "classsokoengine_1_1SokobanPlusDataError" ],
    [ "SokobanTessellation", "classsokoengine_1_1SokobanTessellation.html", "classsokoengine_1_1SokobanTessellation" ],
    [ "Tessellation", "classsokoengine_1_1Tessellation.html", "classsokoengine_1_1Tessellation" ],
    [ "TextUtils", "classsokoengine_1_1TextUtils.html", "classsokoengine_1_1TextUtils" ],
    [ "TriobanBoard", "classsokoengine_1_1TriobanBoard.html", "classsokoengine_1_1TriobanBoard" ],
    [ "TriobanTessellation", "classsokoengine_1_1TriobanTessellation.html", "classsokoengine_1_1TriobanTessellation" ],
    [ "UnknownDirectionError", "classsokoengine_1_1UnknownDirectionError.html", "classsokoengine_1_1UnknownDirectionError" ],
    [ "UnknownTessellationError", "classsokoengine_1_1UnknownTessellationError.html", "classsokoengine_1_1UnknownTessellationError" ],
    [ "VariantBoard", "classsokoengine_1_1VariantBoard.html", "classsokoengine_1_1VariantBoard" ]
];